### PR TITLE
Failing test

### PR DESCRIPTION
**Pull request by mitar**
See: https://github.com/jquery/jquery/issues/2968

### CODE REVIEW

**Comment by jonschlinkert** [comment]
Closing since this is incorrect: 

```js
 expect(isPlainObject(Object.assign(Object.create({foo: "bar"}), {bar: "foo"})) ).to.be.false;
```

That is definitely a plain object.

**Comment by mitar** [comment]
What? It is not, because `{foo: "bar"}` is a prototype which makes it a non-plain.

**Comment by jonschlinkert** [comment]
I don't know where you're getting your information about what a plain object is, but a plain object is an object created by the `Object` constructor. Period. 

```js
var foo = Object.assign(Object.create({a: 'b'}), {c: 'd'});
console.log(foo.constructor.name);
//=> 'Object'
```

Even if that wasn't the definition of a plain object, the description of this project is:

> Return `true` if the given `value` is an object created by the `Object` constructor.

**Comment by mitar** [comment]
Yes, there is a difference between `new Object()` (`Object` constructor) and `Object.create`. The latter takes as the first argument the prototype of the resulting object, which makes it non-plain.

`new Object()` is different from `Object.create({})`.

screen shot 2017-07-11 at 11 22 54 pm

See one more level in the tree? This makes it non-plain.

**Comment by mitar** [comment]
`Object.create` was made to make inheritance easier in times before ES2016. It makes a subobject of the given object. That is by definition non-plain object.

**Comment by jonschlinkert** [comment]
No, `Object.create()` returns a new object created by the constructor of the object that was passed to it. To create an object with no constructor, you would do `Object.create(null)`. The prototype has nothing to do with it. 

In your initial examples, since `{}` is an instance of `Object`, `Object.create()` uses `Object` to create a new object.

These examples should make it more clear:

```js
var foo = Object.assign(Object.create({a: 'b'}), {c: 'd'});
console.log(foo.constructor)
//=> 'Object'

var foo = Object.assign(Object.create(null), {c: 'd'});
console.log(foo.constructor)
//=> 'undefined'

var foo = Object.assign({c: 'd'}, Object.create(null));
console.log(foo.constructor)
//=> 'Object'
```

If the `constructor` is Object, it's a plain object. I didn't make the rules, I'm just the messenger.

**Comment by mitar** [comment]
Hm, interesting. Thanks for the explanation.

**Pull request closed without merging**
